# Generated by Django 4.2.7 on 2025-07-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Tóm tắt')),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Ảnh đại diện')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Tags (phân cách bằng dấu phẩy)')),
                ('read_time', models.PositiveIntegerField(default=5, verbose_name='Thời gian đọc (phút)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Đã xuất bản')),
                ('featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày xuất bản')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Chủ đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Đã trả lời')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
            ],
            options={
                'verbose_name': 'Tin nhắn liên hệ',
                'verbose_name_plural': 'Tin nhắn liên hệ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('thumbnail', models.ImageField(blank=True, upload_to='courses/', verbose_name='Ảnh thumbnail')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon class (Bootstrap/Font Awesome)')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Thời lượng')),
                ('level', models.CharField(choices=[('beginner', 'Người mới bắt đầu'), ('intermediate', 'Trung cấp'), ('advanced', 'Nâng cao')], default='beginner', max_length=50, verbose_name='Cấp độ')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá')),
                ('course_url', models.URLField(blank=True, verbose_name='Link khóa học')),
                ('enrollment_required', models.BooleanField(default=True, verbose_name='Yêu cầu đăng ký')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Khóa học',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('thumbnail', models.ImageField(blank=True, upload_to='podcast/', verbose_name='Ảnh thumbnail')),
                ('audio_url', models.URLField(blank=True, verbose_name='Link audio')),
                ('video_embed_url', models.TextField(blank=True, verbose_name='Embed code video')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Thời lượng')),
                ('episode_number', models.PositiveIntegerField(unique=True, verbose_name='Số tập')),
                ('season', models.PositiveIntegerField(default=1, verbose_name='Mùa')),
                ('spotify_url', models.URLField(blank=True, verbose_name='Spotify')),
                ('apple_url', models.URLField(blank=True, verbose_name='Apple Podcast')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('is_published', models.BooleanField(default=True, verbose_name='Đã xuất bản')),
                ('featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày xuất bản')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Podcast Episode',
                'verbose_name_plural': 'Podcast Episodes',
                'ordering': ['-episode_number'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('tagline', models.CharField(max_length=200, verbose_name='Tagline')),
                ('bio', models.TextField(verbose_name='Mô tả bản thân')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Tổng học viên')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Tổng lượt xem')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Năm kinh nghiệm')),
                ('courses_created', models.PositiveIntegerField(default=0, verbose_name='Khóa học đã tạo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
