# Generated by Django 4.2.7 on 2025-08-11 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Tóm tắt')),
                ('featured_image', models.URLField(blank=True, help_text='Link đến ảnh đại diện bài viết', verbose_name='Link ảnh đại diện')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Tags (phân cách bằng dấu phẩy)')),
                ('read_time', models.PositiveIntegerField(default=5, verbose_name='Thời gian đọc (phút)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Đã xuất bản')),
                ('featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày xuất bản')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên category')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon class (Bootstrap/Font Awesome)')),
                ('color', models.CharField(default='#007bff', help_text='VD: #007bff', max_length=7, verbose_name='Màu sắc (hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Chủ đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Đã trả lời')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
            ],
            options={
                'verbose_name': 'Tin nhắn liên hệ',
                'verbose_name_plural': 'Tin nhắn liên hệ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('thumbnail', models.URLField(blank=True, help_text='Link đến ảnh thumbnail episode', verbose_name='Link ảnh thumbnail')),
                ('audio_url', models.URLField(blank=True, verbose_name='Link audio')),
                ('video_embed_url', models.TextField(blank=True, verbose_name='Embed code video')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Thời lượng')),
                ('episode_number', models.PositiveIntegerField(unique=True, verbose_name='Số tập')),
                ('season', models.PositiveIntegerField(default=1, verbose_name='Mùa')),
                ('spotify_url', models.URLField(blank=True, verbose_name='Spotify')),
                ('apple_url', models.URLField(blank=True, verbose_name='Apple Podcast')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('is_published', models.BooleanField(default=True, verbose_name='Đã xuất bản')),
                ('featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày xuất bản')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Podcast Episode',
                'verbose_name_plural': 'Podcast Episodes',
                'ordering': ['-episode_number'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('tagline', models.CharField(max_length=200, verbose_name='Tagline')),
                ('bio', models.TextField(verbose_name='Mô tả bản thân')),
                ('avatar', models.URLField(blank=True, help_text='Link đến ảnh đại diện (VD: https://images.unsplash.com/...)', verbose_name='Link ảnh đại diện')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Tổng học viên')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Tổng lượt xem')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Năm kinh nghiệm')),
                ('courses_created', models.PositiveIntegerField(default=0, verbose_name='Khóa học đã tạo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('thumbnail', models.URLField(blank=True, help_text='Link đến ảnh thumbnail project', verbose_name='Link ảnh thumbnail')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon class (Bootstrap/Font Awesome)')),
                ('technologies', models.CharField(blank=True, help_text='VD: Django, React, PostgreSQL', max_length=500, verbose_name='Công nghệ sử dụng')),
                ('duration', models.CharField(blank=True, help_text='VD: 2 tuần, 1 tháng', max_length=50, verbose_name='Thời gian phát triển')),
                ('level', models.CharField(choices=[('beginner', 'Cơ bản'), ('intermediate', 'Trung cấp'), ('advanced', 'Nâng cao')], default='intermediate', max_length=50, verbose_name='Độ khó')),
                ('github_url', models.URLField(blank=True, verbose_name='Link GitHub')),
                ('demo_url', models.URLField(blank=True, verbose_name='Link Demo')),
                ('project_url', models.URLField(blank=True, verbose_name='Link Project')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('completed', models.BooleanField(default=False, verbose_name='Đã hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
