# Generated by Django 4.2.7 on 2025-07-19 15:39

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to=portfolio.models.blog_image_path, verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=portfolio.models.course_thumbnail_path, verbose_name='Ảnh thumbnail'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=portfolio.models.podcast_thumbnail_path, verbose_name='Ảnh thumbnail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=portfolio.models.profile_avatar_path, verbose_name='Ảnh đại diện'),
        ),
    ]
